# Generated by Django 3.2.8 on 2021-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('salary', models.FloatField(verbose_name='Monthly Salary')),
            ],
        ),
    ]
